# Generated by Django 3.1.7 on 2021-03-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=1024)),
            ],
        ),
    ]
