# Generated by Django 3.1.7 on 2021-03-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.country'),
        ),
    ]
