# Generated by Django 3.1.7 on 2021-03-18 15:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_employee_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bank_id', models.CharField(max_length=12)),
                ('bank_name', models.CharField(max_length=64)),
                ('bank_ifsc', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.bankdetail'),
        ),
    ]
