# Generated by Django 3.1.7 on 2021-03-18 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0007_auto_20210318_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='skill_sets',
            field=models.ManyToManyField(blank=True, to='emp.SkillSet'),
        ),
    ]
