# Generated by Django 3.1.7 on 2021-03-18 15:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0008_auto_20210318_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('salary', models.FloatField()),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emp.employee')),
            ],
        ),
    ]
